name: Cleanup

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  container-images:
    runs-on: docker
    name: Container-Images
    steps:
      - name: Cleanup
        uses: https://codeberg.org/jvllmr/forgejo-pkg-cleanup@665c68c4b3a0f13cde416c2b9b95e11f96ef367a # v1.0.2
        with:
          instance: https://codeberg.org
          username: jvllmr
          password: ${{ secrets.PUBLISH_TOKEN }}
          package: ^frans-cache$
          packageType: container
          owner: jvllmr
          keepVersions: ^(?:(?:v)?(?:\d+)(?:\.(\d+))?(?:\.(\d+))?(?:[a|b]\d+)?)?(?:main)?$
          retention: 30m
