name: Cleanup

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  container-images:
    runs-on: docker
    name: Container-Images
    steps:
      - name: Cleanup
        uses: https://codeberg.org/jvllmr/forgejo-pkg-cleanup@4b02e24ed0075ae039873588d8aaf6b43fb4a6b8 # v1.0.1
        with:
          instance: https://codeberg.org
          username: jvllmr
          password: ${{ secrets.PUBLISH_TOKEN }}
          package: ^frans-cache$
          packageType: container
          owner: jvllmr
          keepVersions: ^(?:(?:v)?(?:\d+)(?:\.(\d+))?(?:\.(\d+))?(?:[a|b]\d+)?)?(?:main)?$
          retention: 30m
