name: Publish

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
      - "v*.*.*"

jobs:
  container-publish:
    name: Container
    permissions:
      contents: read
      packages: write
      pull-requests: write
    runs-on: docker
    steps:
      - run: apt-get update
      - run: apt-get install podman buildah ca-certificates -y
      # https://codeberg.org/actions/buildah-simple/src/branch/main/action.yml
      - run: echo root:1:65536 | tee /etc/subuid /etc/subgid
      - run: mv /etc/containers/storage.conf /etc/containers/storage.conf.bak || true
      - run: printf '[storage]\ndriver="vfs"\nrunroot="/run/containers/storage"\ngraphroot="/var/lib/containers/storage"\n' | tee /etc/containers/storage.conf
      - uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-tags: true
          fetch-depth: 0
      - name: Generate version
        run: ./scripts/gen_version.sh
      - name: Get docker tags
        id: metadata
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: |
            codeberg.org/jvllmr/frans
          tags: |
            type=ref,event=pr
            type=ref,event=branch,enable={{is_default_branch}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}
      - name: Create docker config
        run: mkdir -p /root/.docker/ && echo '{"auths":{}}' > /root/.docker/config.json
      - name: Log in to Codeberg registry
        uses: https://github.com/redhat-actions/podman-login@4c93cb1ea36b10156ea541570dc69bc04dffe10e # v1.1.2
        with:
          registry: codeberg.org/jvllmr
          username: jvllmr
          password: ${{ secrets.PUBLISH_TOKEN }}
          auth_file_path: /run/user/0/containers/auth.json
      - name: Build container
        uses: https://github.com/redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        env:
          BUILDAH_ISOLATION: chroot
        with:
          context: .
          containerfiles: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          layers: true
          extra-args: |
            --cache-from codeberg.org/jvllmr/frans-cache
            --cache-to codeberg.org/jvllmr/frans-cache
          # annotations: ${{ steps.metadata.outputs.annotations }}
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
          #cache-from: type=registry,ref=ghcr.io/jvllmr/frans:buildcache
          #cache-to: type=registry,ref=ghcr.io/jvllmr/frans:buildcache,mode=max
      #- name: Comment PR
      #  if: github.repository == 'jvllmr/frans' && github.event_name == 'pull_request'
      #  uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
      #  with:
      #    message: |
      #      🔄 Building container image `ghcr.io/jvllmr/frans:pr-${{ github.event.pull_request.number }}` on commit `${{ github.event.pull_request.head.sha }}`
      #    message-success: |
      #      ✅ Successfully built and pushed container image `ghcr.io/jvllmr/frans:pr-${{ github.event.pull_request.number }}` on commit `${{ github.event.pull_request.head.sha }}`.
      #         You can try it out now
      #    message-failure: |
      #      ❌ Failed to build container image `ghcr.io/jvllmr/frans:pr-${{ github.event.pull_request.number }}` on commit `${{ github.event.pull_request.head.sha }}`
      - name: Push container
        uses: https://github.com/redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          registry: codeberg.org/jvllmr
          username: jvllmr
          password: ${{ secrets.PUBLISH_TOKEN }}
          tags: ${{ steps.metadata.outputs.tags }}
          extra-args: |
            --authfile /run/user/0/containers/auth.json

  helm-lint-test:
    needs:
      - container-publish
    name: Test Helm
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set version
        run: sed -i "s/%VERSION%/0.1.0/g" charts/frans-helm/Chart.yaml

      - name: Set app version
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            APPVERSION="pr-${GITHUB_PR_NUMBER}"
          else
            APPVERSION="main"
          fi
          echo "Set app version to $APPVERSION"
          sed -i "s/%APPVERSION%/$APPVERSION/g" charts/frans-helm/Chart.yaml
      - name: Set up Helm
        uses: https://github.com/azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - uses: https://github.com/actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14.2"
          check-latest: true

      - name: Set up chart-testing
        uses: https://github.com/helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
        with:
          yamale_version: "6.0.0"

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH} --check-version-increment=false
        env:
          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: https://github.com/helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
      - name: Setup postgres
        if: steps.list-changed.outputs.changed == 'true'
        run: kubectl apply -f .forgejo/manifests/postgres.yaml
      - name: Setup pocket-id
        if: steps.list-changed.outputs.changed == 'true'
        run: kubectl apply -f .forgejo/manifests/pocketid.yaml
      - name: Change database address
        if: steps.list-changed.outputs.changed == 'true'
        run: "sed -i 's/host: localhost/host: postgres.default.svc.cluster.local/' charts/frans-helm/values.yaml"
      - name: Set database password
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          sed -i 's/password: ""/password: frans/' charts/frans-helm/values.yaml
      - name: Change oidc issuer
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          sed -i 's|issuer: ""|issuer: "http://pocket-id.default.svc.cluster.local:1411"|' charts/frans-helm/values.yaml
      - name: Change oidc client id
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          sed -i 's|client_id: ""|client_id: "test"|' charts/frans-helm/values.yaml
      - name: Waiting for pods to be ready
        if: steps.list-changed.outputs.changed == 'true'
        run: kubectl wait --for=condition=Ready pod --all --namespace=default --timeout=180s
      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --chart-dirs charts --target-branch ${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH}
        env:
          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

  helm-publish:
    needs:
      - container-publish
      # - helm-lint-test
    name: Helm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install helm
        uses: https://github.com/Azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - name: Set version
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          SHA=$(git rev-parse --short HEAD)
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            # Use tag, strip leading 'v'
            VERSION="${GITHUB_REF_NAME#v}"
            APPVERSION="${GITHUB_REF_NAME}"
          else
            # Get previous tag (most recent tag reachable from current commit)
            PREV_TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
            PREV_TAG="${PREV_TAG#v}"

            if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
              APPVERSION="pr-${GITHUB_PR_NUMBER}"
              VERSION="${PREV_TAG}+helm-pr-${GITHUB_PR_NUMBER}"
            else
              APPVERSION="main"
              VERSION="${PREV_TAG}+helm-main"
            fi
          fi
          echo "Set chart version to $VERSION"
          echo "Set app version to $APPVERSION"
          sed -i "s/%VERSION%/$VERSION/g" charts/frans-helm/Chart.yaml
          sed -i "s/%APPVERSION%/$APPVERSION/g" charts/frans-helm/Chart.yaml
      - name: Log in to Codeberg Container Registry
        run: |
          echo "${{ secrets.PUBLISH_TOKEN }}" | helm registry login codeberg.org \
            --username jvllmr \
            --password-stdin
      - name: Package and Push Helm Chart
        run: |
          CHART_NAME=frans-helm
          CHART_PATH=charts/${CHART_NAME}
          VERSION=$(yq -r '.version' ${CHART_PATH}/Chart.yaml)

          echo "Packaging ${CHART_NAME} version ${VERSION}"
          helm package ${CHART_PATH} --destination packaged
          echo $(ls packaged)
          echo "Pushing to codeberg.org/${{ github.repository_owner }}/${CHART_NAME}:${VERSION}"
          helm push packaged/${CHART_NAME}-${VERSION}.tgz \
            oci://codeberg.org/${{ github.repository_owner }}
