name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
    name: unittest
    runs-on: docker
    env:
      FRANS_DB_TYPE: postgres
      FRANS_DB_HOST: postgres
      FRANS_DB_USER: postgres
      FRANS_DB_PASSWORD: postgres
      FRANS_DB_NAME: postgres
      FRANS_SMTP_SERVER: smtp
      FRANS_SMTP_PORT: "25"

    services:
      smtp:
        image: docker.io/rnwood/smtp4dev:3.15.0@sha256:25c434c1900a9c5b61e17ead0a774d9e81b80554d05cf64719d69e5ea8c66537

    steps:
      - uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: https://github.com/pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false
      - name: Setup go
        uses: https://github.com/actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ">=1.25.6"
          token: ${{ secrets.GH_PAT }}
      - name: Run pre-build steps
        run: ./scripts/prebuild.sh
      - name: Generate version
        run: ./scripts/gen_version.sh
      - name: Run tests
        run: pnpm test:cover
      - name: Upload coverage to codecov
        if: false
        uses: https://github.com/codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    permissions:
      contents: read
    name: test-build
    runs-on: docker
    steps:
      - uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: https://github.com/pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false
      - name: Install Node.js
        uses: https://github.com/actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.13.0
          cache: "pnpm"
          token: ${{ secrets.GH_PAT }}
      - name: Setup go
        uses: https://github.com/actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ">=1.25.6"
          token: ${{ secrets.GH_PAT }}
      - name: Install dependencies
        run: pnpm install --frozen-lock
      - name: Build
        run: pnpm build
      - name: Upload build
        uses: https://github.com/actions/upload-artifact@c6a366c94c3e0affe28c06c8df20a878f24da3cf # v3.2.2
        with:
          name: build-output
          path: frans
          retention-days: 2
  migration-sqlite:
    needs: build
    permissions:
      contents: read
    name: test-migration-sqlite3
    runs-on: docker
    env:
      FRANS_DB_TYPE: sqlite3

    steps:
      - name: Download artifact from build workflow
        uses: https://github.com/actions/download-artifact@a9bc5e6ef2cb54c177f32aa5726adaa15e7e2d59 # v3.1.0
        with:
          name: build-output
      - run: chmod +x frans
      - name: Run migration
        run: ./frans migrate
  migration-postgres:
    needs: build
    permissions:
      contents: read
    name: test-migration-postgres
    runs-on: docker
    env:
      FRANS_DB_TYPE: postgres
      FRANS_DB_HOST: postgres
      FRANS_DB_USER: postgres
      FRANS_DB_PASSWORD: postgres
      FRANS_DB_NAME: postgres

    services:
      postgres:
        image: docker.io/postgres:18-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Download artifact from build workflow
        uses: https://github.com/actions/download-artifact@a9bc5e6ef2cb54c177f32aa5726adaa15e7e2d59 # v3.1.0
        with:
          name: build-output
      - run: chmod +x frans
      - name: Run migration
        run: ./frans migrate
  migration-mysql:
    needs: build
    permissions:
      contents: read
    name: test-migration-mysql
    runs-on: docker
    env:
      FRANS_DB_TYPE: mysql
      FRANS_DB_HOST: mysql
      FRANS_DB_USER: user
      FRANS_DB_PASSWORD: abc123
      FRANS_DB_NAME: frans

    services:
      mysql:
        image: docker.io/mysql:9.6.0@sha256:e5dc14f6e01c3e577e669337d2855c6d1561b30d8ef2c592e63e4e8a9a52650a
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_USER: user
          MYSQL_PASSWORD: abc123
          MYSQL_DATABASE: frans
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Download artifact from build workflow
        uses: https://github.com/actions/download-artifact@a9bc5e6ef2cb54c177f32aa5726adaa15e7e2d59 # v3.1.0
        with:
          name: build-output
      - run: chmod +x frans
      - name: Run migration
        run: ./frans migrate
