// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/jvllmr/frans/internal/ent/file"
)

// File is the model entity for the File schema.
type File struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Size holds the value of the "size" field.
	Size uint64 `json:"size,omitempty"`
	// Sha512 holds the value of the "sha512" field.
	Sha512 string `json:"sha512,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// LastDownload holds the value of the "last_download" field.
	LastDownload *time.Time `json:"last_download,omitempty"`
	// TimesDownloaded holds the value of the "times_downloaded" field.
	TimesDownloaded uint64 `json:"times_downloaded,omitempty"`
	// ExpiryType holds the value of the "expiry_type" field.
	ExpiryType string `json:"expiry_type,omitempty"`
	// ExpiryTotalDays holds the value of the "expiry_total_days" field.
	ExpiryTotalDays uint8 `json:"expiry_total_days,omitempty"`
	// ExpiryDaysSinceLastDownload holds the value of the "expiry_days_since_last_download" field.
	ExpiryDaysSinceLastDownload uint8 `json:"expiry_days_since_last_download,omitempty"`
	// ExpiryTotalDownloads holds the value of the "expiry_total_downloads" field.
	ExpiryTotalDownloads uint8 `json:"expiry_total_downloads,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FileQuery when eager-loading is set.
	Edges        FileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FileEdges holds the relations/edges for other nodes in the graph.
type FileEdges struct {
	// Tickets holds the value of the tickets edge.
	Tickets []*Ticket `json:"tickets,omitempty"`
	// Grants holds the value of the grants edge.
	Grants []*Grant `json:"grants,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TicketsOrErr returns the Tickets value or an error if the edge
// was not loaded in eager-loading.
func (e FileEdges) TicketsOrErr() ([]*Ticket, error) {
	if e.loadedTypes[0] {
		return e.Tickets, nil
	}
	return nil, &NotLoadedError{edge: "tickets"}
}

// GrantsOrErr returns the Grants value or an error if the edge
// was not loaded in eager-loading.
func (e FileEdges) GrantsOrErr() ([]*Grant, error) {
	if e.loadedTypes[1] {
		return e.Grants, nil
	}
	return nil, &NotLoadedError{edge: "grants"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*File) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case file.FieldSize, file.FieldTimesDownloaded, file.FieldExpiryTotalDays, file.FieldExpiryDaysSinceLastDownload, file.FieldExpiryTotalDownloads:
			values[i] = new(sql.NullInt64)
		case file.FieldName, file.FieldSha512, file.FieldExpiryType:
			values[i] = new(sql.NullString)
		case file.FieldCreatedAt, file.FieldLastDownload:
			values[i] = new(sql.NullTime)
		case file.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the File fields.
func (_m *File) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case file.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case file.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case file.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = uint64(value.Int64)
			}
		case file.FieldSha512:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha512", values[i])
			} else if value.Valid {
				_m.Sha512 = value.String
			}
		case file.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case file.FieldLastDownload:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_download", values[i])
			} else if value.Valid {
				_m.LastDownload = new(time.Time)
				*_m.LastDownload = value.Time
			}
		case file.FieldTimesDownloaded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field times_downloaded", values[i])
			} else if value.Valid {
				_m.TimesDownloaded = uint64(value.Int64)
			}
		case file.FieldExpiryType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field expiry_type", values[i])
			} else if value.Valid {
				_m.ExpiryType = value.String
			}
		case file.FieldExpiryTotalDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expiry_total_days", values[i])
			} else if value.Valid {
				_m.ExpiryTotalDays = uint8(value.Int64)
			}
		case file.FieldExpiryDaysSinceLastDownload:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expiry_days_since_last_download", values[i])
			} else if value.Valid {
				_m.ExpiryDaysSinceLastDownload = uint8(value.Int64)
			}
		case file.FieldExpiryTotalDownloads:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expiry_total_downloads", values[i])
			} else if value.Valid {
				_m.ExpiryTotalDownloads = uint8(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the File.
// This includes values selected through modifiers, order, etc.
func (_m *File) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTickets queries the "tickets" edge of the File entity.
func (_m *File) QueryTickets() *TicketQuery {
	return NewFileClient(_m.config).QueryTickets(_m)
}

// QueryGrants queries the "grants" edge of the File entity.
func (_m *File) QueryGrants() *GrantQuery {
	return NewFileClient(_m.config).QueryGrants(_m)
}

// Update returns a builder for updating this File.
// Note that you need to call File.Unwrap() before calling this method if this File
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *File) Update() *FileUpdateOne {
	return NewFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the File entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *File) Unwrap() *File {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: File is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *File) String() string {
	var builder strings.Builder
	builder.WriteString("File(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("sha512=")
	builder.WriteString(_m.Sha512)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastDownload; v != nil {
		builder.WriteString("last_download=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("times_downloaded=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimesDownloaded))
	builder.WriteString(", ")
	builder.WriteString("expiry_type=")
	builder.WriteString(_m.ExpiryType)
	builder.WriteString(", ")
	builder.WriteString("expiry_total_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpiryTotalDays))
	builder.WriteString(", ")
	builder.WriteString("expiry_days_since_last_download=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpiryDaysSinceLastDownload))
	builder.WriteString(", ")
	builder.WriteString("expiry_total_downloads=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpiryTotalDownloads))
	builder.WriteByte(')')
	return builder.String()
}

// Files is a parsable slice of File.
type Files []*File
