// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jvllmr/frans/internal/ent/file"
	"github.com/jvllmr/frans/internal/ent/filedata"
	"github.com/jvllmr/frans/internal/ent/grant"
	"github.com/jvllmr/frans/internal/ent/ticket"
	"github.com/jvllmr/frans/internal/ent/user"
)

// FileCreate is the builder for creating a File entity.
type FileCreate struct {
	config
	mutation *FileMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *FileCreate) SetName(v string) *FileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FileCreate) SetCreatedAt(v time.Time) *FileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FileCreate) SetNillableCreatedAt(v *time.Time) *FileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetLastDownload sets the "last_download" field.
func (_c *FileCreate) SetLastDownload(v time.Time) *FileCreate {
	_c.mutation.SetLastDownload(v)
	return _c
}

// SetNillableLastDownload sets the "last_download" field if the given value is not nil.
func (_c *FileCreate) SetNillableLastDownload(v *time.Time) *FileCreate {
	if v != nil {
		_c.SetLastDownload(*v)
	}
	return _c
}

// SetTimesDownloaded sets the "times_downloaded" field.
func (_c *FileCreate) SetTimesDownloaded(v uint64) *FileCreate {
	_c.mutation.SetTimesDownloaded(v)
	return _c
}

// SetNillableTimesDownloaded sets the "times_downloaded" field if the given value is not nil.
func (_c *FileCreate) SetNillableTimesDownloaded(v *uint64) *FileCreate {
	if v != nil {
		_c.SetTimesDownloaded(*v)
	}
	return _c
}

// SetExpiryType sets the "expiry_type" field.
func (_c *FileCreate) SetExpiryType(v string) *FileCreate {
	_c.mutation.SetExpiryType(v)
	return _c
}

// SetExpiryTotalDays sets the "expiry_total_days" field.
func (_c *FileCreate) SetExpiryTotalDays(v uint8) *FileCreate {
	_c.mutation.SetExpiryTotalDays(v)
	return _c
}

// SetExpiryDaysSinceLastDownload sets the "expiry_days_since_last_download" field.
func (_c *FileCreate) SetExpiryDaysSinceLastDownload(v uint8) *FileCreate {
	_c.mutation.SetExpiryDaysSinceLastDownload(v)
	return _c
}

// SetExpiryTotalDownloads sets the "expiry_total_downloads" field.
func (_c *FileCreate) SetExpiryTotalDownloads(v uint8) *FileCreate {
	_c.mutation.SetExpiryTotalDownloads(v)
	return _c
}

// SetID sets the "id" field.
func (_c *FileCreate) SetID(v uuid.UUID) *FileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTicketID sets the "ticket" edge to the Ticket entity by ID.
func (_c *FileCreate) SetTicketID(id uuid.UUID) *FileCreate {
	_c.mutation.SetTicketID(id)
	return _c
}

// SetNillableTicketID sets the "ticket" edge to the Ticket entity by ID if the given value is not nil.
func (_c *FileCreate) SetNillableTicketID(id *uuid.UUID) *FileCreate {
	if id != nil {
		_c = _c.SetTicketID(*id)
	}
	return _c
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_c *FileCreate) SetTicket(v *Ticket) *FileCreate {
	return _c.SetTicketID(v.ID)
}

// SetGrantID sets the "grant" edge to the Grant entity by ID.
func (_c *FileCreate) SetGrantID(id uuid.UUID) *FileCreate {
	_c.mutation.SetGrantID(id)
	return _c
}

// SetNillableGrantID sets the "grant" edge to the Grant entity by ID if the given value is not nil.
func (_c *FileCreate) SetNillableGrantID(id *uuid.UUID) *FileCreate {
	if id != nil {
		_c = _c.SetGrantID(*id)
	}
	return _c
}

// SetGrant sets the "grant" edge to the Grant entity.
func (_c *FileCreate) SetGrant(v *Grant) *FileCreate {
	return _c.SetGrantID(v.ID)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *FileCreate) SetOwnerID(id uuid.UUID) *FileCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *FileCreate) SetOwner(v *User) *FileCreate {
	return _c.SetOwnerID(v.ID)
}

// SetDataID sets the "data" edge to the FileData entity by ID.
func (_c *FileCreate) SetDataID(id string) *FileCreate {
	_c.mutation.SetDataID(id)
	return _c
}

// SetData sets the "data" edge to the FileData entity.
func (_c *FileCreate) SetData(v *FileData) *FileCreate {
	return _c.SetDataID(v.ID)
}

// Mutation returns the FileMutation object of the builder.
func (_c *FileCreate) Mutation() *FileMutation {
	return _c.mutation
}

// Save creates the File in the database.
func (_c *FileCreate) Save(ctx context.Context) (*File, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileCreate) SaveX(ctx context.Context) *File {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := file.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.TimesDownloaded(); !ok {
		v := file.DefaultTimesDownloaded
		_c.mutation.SetTimesDownloaded(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "File.name"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "File.created_at"`)}
	}
	if _, ok := _c.mutation.TimesDownloaded(); !ok {
		return &ValidationError{Name: "times_downloaded", err: errors.New(`ent: missing required field "File.times_downloaded"`)}
	}
	if _, ok := _c.mutation.ExpiryType(); !ok {
		return &ValidationError{Name: "expiry_type", err: errors.New(`ent: missing required field "File.expiry_type"`)}
	}
	if _, ok := _c.mutation.ExpiryTotalDays(); !ok {
		return &ValidationError{Name: "expiry_total_days", err: errors.New(`ent: missing required field "File.expiry_total_days"`)}
	}
	if _, ok := _c.mutation.ExpiryDaysSinceLastDownload(); !ok {
		return &ValidationError{Name: "expiry_days_since_last_download", err: errors.New(`ent: missing required field "File.expiry_days_since_last_download"`)}
	}
	if _, ok := _c.mutation.ExpiryTotalDownloads(); !ok {
		return &ValidationError{Name: "expiry_total_downloads", err: errors.New(`ent: missing required field "File.expiry_total_downloads"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "File.owner"`)}
	}
	if len(_c.mutation.DataIDs()) == 0 {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required edge "File.data"`)}
	}
	return nil
}

func (_c *FileCreate) sqlSave(ctx context.Context) (*File, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileCreate) createSpec() (*File, *sqlgraph.CreateSpec) {
	var (
		_node = &File{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(file.Table, sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(file.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(file.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastDownload(); ok {
		_spec.SetField(file.FieldLastDownload, field.TypeTime, value)
		_node.LastDownload = &value
	}
	if value, ok := _c.mutation.TimesDownloaded(); ok {
		_spec.SetField(file.FieldTimesDownloaded, field.TypeUint64, value)
		_node.TimesDownloaded = value
	}
	if value, ok := _c.mutation.ExpiryType(); ok {
		_spec.SetField(file.FieldExpiryType, field.TypeString, value)
		_node.ExpiryType = value
	}
	if value, ok := _c.mutation.ExpiryTotalDays(); ok {
		_spec.SetField(file.FieldExpiryTotalDays, field.TypeUint8, value)
		_node.ExpiryTotalDays = value
	}
	if value, ok := _c.mutation.ExpiryDaysSinceLastDownload(); ok {
		_spec.SetField(file.FieldExpiryDaysSinceLastDownload, field.TypeUint8, value)
		_node.ExpiryDaysSinceLastDownload = value
	}
	if value, ok := _c.mutation.ExpiryTotalDownloads(); ok {
		_spec.SetField(file.FieldExpiryTotalDownloads, field.TypeUint8, value)
		_node.ExpiryTotalDownloads = value
	}
	if nodes := _c.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.TicketTable,
			Columns: []string{file.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ticket_files = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.GrantTable,
			Columns: []string{file.GrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.grant_files = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.OwnerTable,
			Columns: []string{file.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_files = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   file.DataTable,
			Columns: []string{file.DataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filedata.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.file_data = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileCreateBulk is the builder for creating many File entities in bulk.
type FileCreateBulk struct {
	config
	err      error
	builders []*FileCreate
}

// Save creates the File entities in the database.
func (_c *FileCreateBulk) Save(ctx context.Context) ([]*File, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*File, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileCreateBulk) SaveX(ctx context.Context) []*File {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
