// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jvllmr/frans/internal/ent/file"
	"github.com/jvllmr/frans/internal/ent/shareaccesstoken"
	"github.com/jvllmr/frans/internal/ent/ticket"
	"github.com/jvllmr/frans/internal/ent/user"
)

// TicketCreate is the builder for creating a Ticket entity.
type TicketCreate struct {
	config
	mutation *TicketMutation
	hooks    []Hook
}

// SetComment sets the "comment" field.
func (_c *TicketCreate) SetComment(v string) *TicketCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *TicketCreate) SetNillableComment(v *string) *TicketCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetExpiryType sets the "expiryType" field.
func (_c *TicketCreate) SetExpiryType(v string) *TicketCreate {
	_c.mutation.SetExpiryType(v)
	return _c
}

// SetHashedPassword sets the "hashed_password" field.
func (_c *TicketCreate) SetHashedPassword(v string) *TicketCreate {
	_c.mutation.SetHashedPassword(v)
	return _c
}

// SetSalt sets the "salt" field.
func (_c *TicketCreate) SetSalt(v string) *TicketCreate {
	_c.mutation.SetSalt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketCreate) SetCreatedAt(v time.Time) *TicketCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableCreatedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiryTotalDays sets the "expiry_total_days" field.
func (_c *TicketCreate) SetExpiryTotalDays(v uint8) *TicketCreate {
	_c.mutation.SetExpiryTotalDays(v)
	return _c
}

// SetExpiryDaysSinceLastDownload sets the "expiry_days_since_last_download" field.
func (_c *TicketCreate) SetExpiryDaysSinceLastDownload(v uint8) *TicketCreate {
	_c.mutation.SetExpiryDaysSinceLastDownload(v)
	return _c
}

// SetExpiryTotalDownloads sets the "expiry_total_downloads" field.
func (_c *TicketCreate) SetExpiryTotalDownloads(v uint8) *TicketCreate {
	_c.mutation.SetExpiryTotalDownloads(v)
	return _c
}

// SetEmailOnDownload sets the "email_on_download" field.
func (_c *TicketCreate) SetEmailOnDownload(v string) *TicketCreate {
	_c.mutation.SetEmailOnDownload(v)
	return _c
}

// SetNillableEmailOnDownload sets the "email_on_download" field if the given value is not nil.
func (_c *TicketCreate) SetNillableEmailOnDownload(v *string) *TicketCreate {
	if v != nil {
		_c.SetEmailOnDownload(*v)
	}
	return _c
}

// SetCreatorLang sets the "creator_lang" field.
func (_c *TicketCreate) SetCreatorLang(v string) *TicketCreate {
	_c.mutation.SetCreatorLang(v)
	return _c
}

// SetNillableCreatorLang sets the "creator_lang" field if the given value is not nil.
func (_c *TicketCreate) SetNillableCreatorLang(v *string) *TicketCreate {
	if v != nil {
		_c.SetCreatorLang(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TicketCreate) SetID(v uuid.UUID) *TicketCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_c *TicketCreate) AddFileIDs(ids ...uuid.UUID) *TicketCreate {
	_c.mutation.AddFileIDs(ids...)
	return _c
}

// AddFiles adds the "files" edges to the File entity.
func (_c *TicketCreate) AddFiles(v ...*File) *TicketCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFileIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *TicketCreate) SetOwnerID(id uuid.UUID) *TicketCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_c *TicketCreate) SetNillableOwnerID(id *uuid.UUID) *TicketCreate {
	if id != nil {
		_c = _c.SetOwnerID(*id)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *TicketCreate) SetOwner(v *User) *TicketCreate {
	return _c.SetOwnerID(v.ID)
}

// AddShareaccesstokenIDs adds the "shareaccesstokens" edge to the ShareAccessToken entity by IDs.
func (_c *TicketCreate) AddShareaccesstokenIDs(ids ...string) *TicketCreate {
	_c.mutation.AddShareaccesstokenIDs(ids...)
	return _c
}

// AddShareaccesstokens adds the "shareaccesstokens" edges to the ShareAccessToken entity.
func (_c *TicketCreate) AddShareaccesstokens(v ...*ShareAccessToken) *TicketCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddShareaccesstokenIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_c *TicketCreate) Mutation() *TicketMutation {
	return _c.mutation
}

// Save creates the Ticket in the database.
func (_c *TicketCreate) Save(ctx context.Context) (*Ticket, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketCreate) SaveX(ctx context.Context) *Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticket.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.CreatorLang(); !ok {
		v := ticket.DefaultCreatorLang
		_c.mutation.SetCreatorLang(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketCreate) check() error {
	if _, ok := _c.mutation.ExpiryType(); !ok {
		return &ValidationError{Name: "expiryType", err: errors.New(`ent: missing required field "Ticket.expiryType"`)}
	}
	if _, ok := _c.mutation.HashedPassword(); !ok {
		return &ValidationError{Name: "hashed_password", err: errors.New(`ent: missing required field "Ticket.hashed_password"`)}
	}
	if _, ok := _c.mutation.Salt(); !ok {
		return &ValidationError{Name: "salt", err: errors.New(`ent: missing required field "Ticket.salt"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ticket.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiryTotalDays(); !ok {
		return &ValidationError{Name: "expiry_total_days", err: errors.New(`ent: missing required field "Ticket.expiry_total_days"`)}
	}
	if _, ok := _c.mutation.ExpiryDaysSinceLastDownload(); !ok {
		return &ValidationError{Name: "expiry_days_since_last_download", err: errors.New(`ent: missing required field "Ticket.expiry_days_since_last_download"`)}
	}
	if _, ok := _c.mutation.ExpiryTotalDownloads(); !ok {
		return &ValidationError{Name: "expiry_total_downloads", err: errors.New(`ent: missing required field "Ticket.expiry_total_downloads"`)}
	}
	if _, ok := _c.mutation.CreatorLang(); !ok {
		return &ValidationError{Name: "creator_lang", err: errors.New(`ent: missing required field "Ticket.creator_lang"`)}
	}
	return nil
}

func (_c *TicketCreate) sqlSave(ctx context.Context) (*Ticket, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketCreate) createSpec() (*Ticket, *sqlgraph.CreateSpec) {
	var (
		_node = &Ticket{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticket.Table, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(ticket.FieldComment, field.TypeString, value)
		_node.Comment = &value
	}
	if value, ok := _c.mutation.ExpiryType(); ok {
		_spec.SetField(ticket.FieldExpiryType, field.TypeString, value)
		_node.ExpiryType = value
	}
	if value, ok := _c.mutation.HashedPassword(); ok {
		_spec.SetField(ticket.FieldHashedPassword, field.TypeString, value)
		_node.HashedPassword = value
	}
	if value, ok := _c.mutation.Salt(); ok {
		_spec.SetField(ticket.FieldSalt, field.TypeString, value)
		_node.Salt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticket.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiryTotalDays(); ok {
		_spec.SetField(ticket.FieldExpiryTotalDays, field.TypeUint8, value)
		_node.ExpiryTotalDays = value
	}
	if value, ok := _c.mutation.ExpiryDaysSinceLastDownload(); ok {
		_spec.SetField(ticket.FieldExpiryDaysSinceLastDownload, field.TypeUint8, value)
		_node.ExpiryDaysSinceLastDownload = value
	}
	if value, ok := _c.mutation.ExpiryTotalDownloads(); ok {
		_spec.SetField(ticket.FieldExpiryTotalDownloads, field.TypeUint8, value)
		_node.ExpiryTotalDownloads = value
	}
	if value, ok := _c.mutation.EmailOnDownload(); ok {
		_spec.SetField(ticket.FieldEmailOnDownload, field.TypeString, value)
		_node.EmailOnDownload = &value
	}
	if value, ok := _c.mutation.CreatorLang(); ok {
		_spec.SetField(ticket.FieldCreatorLang, field.TypeString, value)
		_node.CreatorLang = value
	}
	if nodes := _c.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ticket.FilesTable,
			Columns: ticket.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.OwnerTable,
			Columns: []string{ticket.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_tickets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ShareaccesstokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.ShareaccesstokensTable,
			Columns: []string{ticket.ShareaccesstokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shareaccesstoken.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TicketCreateBulk is the builder for creating many Ticket entities in bulk.
type TicketCreateBulk struct {
	config
	err      error
	builders []*TicketCreate
}

// Save creates the Ticket entities in the database.
func (_c *TicketCreateBulk) Save(ctx context.Context) ([]*Ticket, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ticket, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketCreateBulk) SaveX(ctx context.Context) []*Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
