apiVersion: v1
kind: Pod
metadata:
  name: pocket-id
  labels:
    app.kubernetes.io/name: pocket-id
spec:
  containers:
    - name: pocket-id
      image: ghcr.io/pocket-id/pocket-id:v1
      ports:
        - containerPort: 1411
      env:
        - name: APP_URL
          value: http://pocket-id:1411
        - name: TRUST_PROXY
          value: "false"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: pocket-id
spec:
  selector:
    app.kubernetes.io/name: pocket-id
  ports:
    - port: 1411
      targetPort: 1411
