-- Create "files" table
CREATE TABLE "files" (
  "id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "size" bigint NOT NULL,
  "sha512" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "last_download" timestamptz NULL,
  "times_downloaded" bigint NOT NULL DEFAULT 0,
  "expiry_type" character varying NOT NULL,
  "expiry_total_days" smallint NOT NULL,
  "expiry_days_since_last_download" smallint NOT NULL,
  "expiry_total_downloads" smallint NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "users" table
CREATE TABLE "users" (
  "id" uuid NOT NULL,
  "username" character varying NOT NULL,
  "full_name" character varying NOT NULL,
  "email" character varying NOT NULL,
  "groups" jsonb NOT NULL,
  "is_admin" boolean NOT NULL,
  "created_at" timestamptz NOT NULL,
  "submitted_tickets" bigint NOT NULL DEFAULT 0,
  "submitted_grants" bigint NOT NULL DEFAULT 0,
  "total_data_size" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
-- Create "grants" table
CREATE TABLE "grants" (
  "id" uuid NOT NULL,
  "comment" character varying NULL,
  "expiry_type" character varying NOT NULL,
  "hashed_password" character varying NOT NULL,
  "salt" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "expiry_total_days" smallint NOT NULL,
  "expiry_days_since_last_upload" smallint NOT NULL,
  "expiry_total_uploads" smallint NOT NULL,
  "file_expiry_type" character varying NOT NULL,
  "file_expiry_total_days" smallint NOT NULL,
  "file_expiry_days_since_last_download" smallint NOT NULL,
  "file_expiry_total_downloads" smallint NOT NULL,
  "last_upload" timestamptz NULL,
  "times_uploaded" bigint NOT NULL DEFAULT 0,
  "email_on_upload" character varying NULL,
  "creator_lang" character varying NOT NULL DEFAULT 'en',
  "user_grants" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "grants_users_grants" FOREIGN KEY ("user_grants") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "grant_files" table
CREATE TABLE "grant_files" (
  "grant_id" uuid NOT NULL,
  "file_id" uuid NOT NULL,
  PRIMARY KEY ("grant_id", "file_id"),
  CONSTRAINT "grant_files_file_id" FOREIGN KEY ("file_id") REFERENCES "files" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "grant_files_grant_id" FOREIGN KEY ("grant_id") REFERENCES "grants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "sessions" table
CREATE TABLE "sessions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "id_token" character varying NOT NULL,
  "expire" timestamptz NOT NULL,
  "refresh_token" character varying NOT NULL,
  "user_sessions" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sessions_users_sessions" FOREIGN KEY ("user_sessions") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "sessions_id_token_key" to table: "sessions"
CREATE UNIQUE INDEX "sessions_id_token_key" ON "sessions" ("id_token");
-- Create "tickets" table
CREATE TABLE "tickets" (
  "id" uuid NOT NULL,
  "comment" character varying NULL,
  "expiry_type" character varying NOT NULL,
  "hashed_password" character varying NOT NULL,
  "salt" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "expiry_total_days" smallint NOT NULL,
  "expiry_days_since_last_download" smallint NOT NULL,
  "expiry_total_downloads" smallint NOT NULL,
  "email_on_download" character varying NULL,
  "creator_lang" character varying NOT NULL DEFAULT 'en',
  "user_tickets" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tickets_users_tickets" FOREIGN KEY ("user_tickets") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "share_access_tokens" table
CREATE TABLE "share_access_tokens" (
  "id" character varying NOT NULL,
  "expiry" timestamptz NOT NULL,
  "grant_shareaccesstokens" uuid NULL,
  "ticket_shareaccesstokens" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "share_access_tokens_grants_shareaccesstokens" FOREIGN KEY ("grant_shareaccesstokens") REFERENCES "grants" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "share_access_tokens_tickets_shareaccesstokens" FOREIGN KEY ("ticket_shareaccesstokens") REFERENCES "tickets" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "ticket_files" table
CREATE TABLE "ticket_files" (
  "ticket_id" uuid NOT NULL,
  "file_id" uuid NOT NULL,
  PRIMARY KEY ("ticket_id", "file_id"),
  CONSTRAINT "ticket_files_file_id" FOREIGN KEY ("file_id") REFERENCES "files" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "ticket_files_ticket_id" FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
