// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jvllmr/frans/pkg/ent/shareaccesstoken"
	"github.com/jvllmr/frans/pkg/ent/ticket"
)

// ShareAccessTokenCreate is the builder for creating a ShareAccessToken entity.
type ShareAccessTokenCreate struct {
	config
	mutation *ShareAccessTokenMutation
	hooks    []Hook
}

// SetExpiry sets the "expiry" field.
func (satc *ShareAccessTokenCreate) SetExpiry(t time.Time) *ShareAccessTokenCreate {
	satc.mutation.SetExpiry(t)
	return satc
}

// SetID sets the "id" field.
func (satc *ShareAccessTokenCreate) SetID(s string) *ShareAccessTokenCreate {
	satc.mutation.SetID(s)
	return satc
}

// SetTicketID sets the "ticket" edge to the Ticket entity by ID.
func (satc *ShareAccessTokenCreate) SetTicketID(id uuid.UUID) *ShareAccessTokenCreate {
	satc.mutation.SetTicketID(id)
	return satc
}

// SetNillableTicketID sets the "ticket" edge to the Ticket entity by ID if the given value is not nil.
func (satc *ShareAccessTokenCreate) SetNillableTicketID(id *uuid.UUID) *ShareAccessTokenCreate {
	if id != nil {
		satc = satc.SetTicketID(*id)
	}
	return satc
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (satc *ShareAccessTokenCreate) SetTicket(t *Ticket) *ShareAccessTokenCreate {
	return satc.SetTicketID(t.ID)
}

// Mutation returns the ShareAccessTokenMutation object of the builder.
func (satc *ShareAccessTokenCreate) Mutation() *ShareAccessTokenMutation {
	return satc.mutation
}

// Save creates the ShareAccessToken in the database.
func (satc *ShareAccessTokenCreate) Save(ctx context.Context) (*ShareAccessToken, error) {
	return withHooks(ctx, satc.sqlSave, satc.mutation, satc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (satc *ShareAccessTokenCreate) SaveX(ctx context.Context) *ShareAccessToken {
	v, err := satc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (satc *ShareAccessTokenCreate) Exec(ctx context.Context) error {
	_, err := satc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (satc *ShareAccessTokenCreate) ExecX(ctx context.Context) {
	if err := satc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (satc *ShareAccessTokenCreate) check() error {
	if _, ok := satc.mutation.Expiry(); !ok {
		return &ValidationError{Name: "expiry", err: errors.New(`ent: missing required field "ShareAccessToken.expiry"`)}
	}
	return nil
}

func (satc *ShareAccessTokenCreate) sqlSave(ctx context.Context) (*ShareAccessToken, error) {
	if err := satc.check(); err != nil {
		return nil, err
	}
	_node, _spec := satc.createSpec()
	if err := sqlgraph.CreateNode(ctx, satc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ShareAccessToken.ID type: %T", _spec.ID.Value)
		}
	}
	satc.mutation.id = &_node.ID
	satc.mutation.done = true
	return _node, nil
}

func (satc *ShareAccessTokenCreate) createSpec() (*ShareAccessToken, *sqlgraph.CreateSpec) {
	var (
		_node = &ShareAccessToken{config: satc.config}
		_spec = sqlgraph.NewCreateSpec(shareaccesstoken.Table, sqlgraph.NewFieldSpec(shareaccesstoken.FieldID, field.TypeString))
	)
	if id, ok := satc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := satc.mutation.Expiry(); ok {
		_spec.SetField(shareaccesstoken.FieldExpiry, field.TypeTime, value)
		_node.Expiry = value
	}
	if nodes := satc.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shareaccesstoken.TicketTable,
			Columns: []string{shareaccesstoken.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ticket_shareaccesstokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShareAccessTokenCreateBulk is the builder for creating many ShareAccessToken entities in bulk.
type ShareAccessTokenCreateBulk struct {
	config
	err      error
	builders []*ShareAccessTokenCreate
}

// Save creates the ShareAccessToken entities in the database.
func (satcb *ShareAccessTokenCreateBulk) Save(ctx context.Context) ([]*ShareAccessToken, error) {
	if satcb.err != nil {
		return nil, satcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(satcb.builders))
	nodes := make([]*ShareAccessToken, len(satcb.builders))
	mutators := make([]Mutator, len(satcb.builders))
	for i := range satcb.builders {
		func(i int, root context.Context) {
			builder := satcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShareAccessTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, satcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, satcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, satcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (satcb *ShareAccessTokenCreateBulk) SaveX(ctx context.Context) []*ShareAccessToken {
	v, err := satcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (satcb *ShareAccessTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := satcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (satcb *ShareAccessTokenCreateBulk) ExecX(ctx context.Context) {
	if err := satcb.Exec(ctx); err != nil {
		panic(err)
	}
}
