// Code generated by ent, DO NOT EDIT.

package file

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the file type in the database.
	Label = "file"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldLastDownload holds the string denoting the last_download field in the database.
	FieldLastDownload = "last_download"
	// FieldTimesDownloaded holds the string denoting the times_downloaded field in the database.
	FieldTimesDownloaded = "times_downloaded"
	// FieldExpiryType holds the string denoting the expiry_type field in the database.
	FieldExpiryType = "expiry_type"
	// FieldExpiryTotalDays holds the string denoting the expiry_total_days field in the database.
	FieldExpiryTotalDays = "expiry_total_days"
	// FieldExpiryDaysSinceLastDownload holds the string denoting the expiry_days_since_last_download field in the database.
	FieldExpiryDaysSinceLastDownload = "expiry_days_since_last_download"
	// FieldExpiryTotalDownloads holds the string denoting the expiry_total_downloads field in the database.
	FieldExpiryTotalDownloads = "expiry_total_downloads"
	// EdgeTicket holds the string denoting the ticket edge name in mutations.
	EdgeTicket = "ticket"
	// EdgeGrant holds the string denoting the grant edge name in mutations.
	EdgeGrant = "grant"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeData holds the string denoting the data edge name in mutations.
	EdgeData = "data"
	// Table holds the table name of the file in the database.
	Table = "files"
	// TicketTable is the table that holds the ticket relation/edge.
	TicketTable = "files"
	// TicketInverseTable is the table name for the Ticket entity.
	// It exists in this package in order to avoid circular dependency with the "ticket" package.
	TicketInverseTable = "tickets"
	// TicketColumn is the table column denoting the ticket relation/edge.
	TicketColumn = "ticket_files"
	// GrantTable is the table that holds the grant relation/edge.
	GrantTable = "files"
	// GrantInverseTable is the table name for the Grant entity.
	// It exists in this package in order to avoid circular dependency with the "grant" package.
	GrantInverseTable = "grants"
	// GrantColumn is the table column denoting the grant relation/edge.
	GrantColumn = "grant_files"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "files"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_files"
	// DataTable is the table that holds the data relation/edge.
	DataTable = "files"
	// DataInverseTable is the table name for the FileData entity.
	// It exists in this package in order to avoid circular dependency with the "filedata" package.
	DataInverseTable = "file_data"
	// DataColumn is the table column denoting the data relation/edge.
	DataColumn = "file_data"
)

// Columns holds all SQL columns for file fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreatedAt,
	FieldLastDownload,
	FieldTimesDownloaded,
	FieldExpiryType,
	FieldExpiryTotalDays,
	FieldExpiryDaysSinceLastDownload,
	FieldExpiryTotalDownloads,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "files"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"file_data",
	"grant_files",
	"ticket_files",
	"user_files",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultTimesDownloaded holds the default value on creation for the "times_downloaded" field.
	DefaultTimesDownloaded uint64
)

// OrderOption defines the ordering options for the File queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByLastDownload orders the results by the last_download field.
func ByLastDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDownload, opts...).ToFunc()
}

// ByTimesDownloaded orders the results by the times_downloaded field.
func ByTimesDownloaded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimesDownloaded, opts...).ToFunc()
}

// ByExpiryType orders the results by the expiry_type field.
func ByExpiryType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiryType, opts...).ToFunc()
}

// ByExpiryTotalDays orders the results by the expiry_total_days field.
func ByExpiryTotalDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiryTotalDays, opts...).ToFunc()
}

// ByExpiryDaysSinceLastDownload orders the results by the expiry_days_since_last_download field.
func ByExpiryDaysSinceLastDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiryDaysSinceLastDownload, opts...).ToFunc()
}

// ByExpiryTotalDownloads orders the results by the expiry_total_downloads field.
func ByExpiryTotalDownloads(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiryTotalDownloads, opts...).ToFunc()
}

// ByTicketField orders the results by ticket field.
func ByTicketField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTicketStep(), sql.OrderByField(field, opts...))
	}
}

// ByGrantField orders the results by grant field.
func ByGrantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGrantStep(), sql.OrderByField(field, opts...))
	}
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByDataField orders the results by data field.
func ByDataField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDataStep(), sql.OrderByField(field, opts...))
	}
}
func newTicketStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TicketInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
	)
}
func newGrantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GrantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GrantTable, GrantColumn),
	)
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newDataStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DataInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, DataTable, DataColumn),
	)
}
