apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  containers:
    - name: postgres
      image: postgres:18
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: frans
        - name: POSTGRES_PASSWORD
          value: frans
        - name: POSTGRES_DB
          value: frans
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - port: 5432
      targetPort: 5432
