name: Helm

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: lint-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set version
        run: sed -i "s/%VERSION%/$GITHUB_REF_NAME/g" charts/frans/Chart.yaml
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            --username ${GITHUB_ACTOR} \
            --password-stdin
      - name: Package and Push Helm Chart
        run: |
          CHART_NAME=frans
          CHART_PATH=charts/${CHART_NAME}
          VERSION=$(grep '^version:' ${CHART_PATH}/Chart.yaml | awk '{print $2}')

          echo "Packaging ${CHART_NAME} version ${VERSION}"
          helm package ${CHART_PATH} --destination packaged

          echo "Pushing to ghcr.io/${{ github.repository_owner }}/${CHART_NAME}:${VERSION}"
          helm push packaged/${CHART_NAME}-${VERSION}.tgz \
            oci://ghcr.io/${{ github.repository_owner }}

  lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set version
        run: sed -i "s/%VERSION%/0.1.0/g" charts/frans/Chart.yaml
      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.x"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH}
        env:
          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --chart-dirs charts --target-branch ${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH}
        env:
          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
