name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  migration-sqlite:
    permissions:
      contents: read
    name: migration-sqlite
    runs-on: ubuntu-latest
    env:
      FRANS_DB_TYPE: sqlite

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      - name: Run migration
        run: go run main.go migrate
  migration-postgres:
    permissions:
      contents: read
    name: migration-postgres
    runs-on: ubuntu-latest
    env:
      FRANS_DB_TYPE: postgres
      FRANS_DB_HOST: postgres
      FRANS_DB_USER: postgres
      FRANS_DB_PASSWORD: postgres
      FRANS_DB_NAME: postgres

    services:
      postgres:
        image: docker.io/posgres:17
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      - name: Run migration
        run: go run main.go migrate
