name: Container

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish
    permissions:
      contents: read
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
          tags: true
          fetch-depth: 0
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Get docker tags
        id: metadata
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            ghcr.io/jvllmr/frans
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate version
        run: ./scripts/gen_version.sh
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          annotations: ${{ steps.metadata.outputs.annotations }}
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
          cache-from: type=registry,ref=ghcr.io/jvllmr/flay:buildcache
          cache-to: type=registry,ref=ghcr.io/jvllmr/flay:buildcache,mode=max
      - name: Comment PR
        if: github.repository == 'jvllmr/frans' && github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          message: |
            🔄 Building container image `ghcr.io/jvllmr/flay:pr-${{ github.event.pull_request.number }}` on commit `${{ github.event.pull_request.head.sha }}`
          message-success: |
            ✅ Successfully built and pushed container image `ghcr.io/jvllmr/flay:pr-${{ github.event.pull_request.number }}` on commit `${{ github.event.pull_request.head.sha }}`.
               You can try it out now
          message-failure: |
            ❌ Failed to build container image `ghcr.io/jvllmr/flay:pr-${{ github.event.pull_request.number }}` on commit `${{ github.event.pull_request.head.sha }}`
